name: EAS build

on:
  workflow_call:
    inputs:
      platform:
        description: Platform to build the preview on
        required: true
        type: string
      profile:
        description: Name of the build profile from eas.json
        required: true
        type: string

  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build the preview on
        required: true
        type: choice
        default: android
        options:
          - android
          - ios
      profile:
        description: Name of the build profile from eas.json
        required: true
        type: choice
        default: preview
        options:
          - preview
          - production

jobs:
  build:
    if:  ${{ inputs.platform == 'android' || inputs.platform == 'ios' }}
    runs-on: ["${{ inputs.platform == 'ios' && 'macos-14' || 'ubuntu-latest' }}", "${{ inputs.platform == 'ios' && 'macos-14' || 'ubuntu-latest' }}"]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        if: inputs.platform == 'android'
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277 # v3.2.1
        if: inputs.platform == 'android'
        with:
          cmdline-tools-version: 11076708 # See https://developer.android.com/studio#command-line-tools-only

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Build app
        env:
          SENTRY_ALLOW_FAILURE: "true"
          EXPO_PUBLIC_SENTRY_DSN: ${{ secrets.EXPO_PUBLIC_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          eas build \
            --profile ${{ inputs.profile }} \
            --platform ${{ inputs.platform }} \
            --local \
            --non-interactive \
            --output ${{ inputs.platform == 'ios' && 'build.ipa' || 'build.apk' }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.platform }}
          path: ${{ inputs.platform == 'ios' && 'build.ipa' || 'build.apk' }}
