name: Trigger release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run?
        type: boolean
        required: true
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Release
        uses: cycjimmy/semantic-release-action@c0334274aaaa912f0cd6f5b02b9710691509b1dc # v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        with:
          dry_run: ${{ github.event.inputs.dry_run }}
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
